# Generated by Django 3.1.5 on 2021-01-26 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextended',
            old_name='userExtended_id',
            new_name='id',
        ),
    ]
